# -*- coding: utf-8 -*-
"""CornOrb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xc3_gnGgR0m9N04JQOAB3rbn2jMDb9cl

Module 1: Keratoconus Detection


  → CNN + Classical + Clinical


  → 5857 features


  → XGBoost


  → Outputs kc_probability

Module 2: Surgery Decision (ML-based)


  → Explicit interpretable features (6)


  → XGBoost (per-procedure or multiclass)

  
  → Confidence-aware abstention
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install opencv-python scikit-image tqdm

import os
import cv2
import numpy as np
from skimage import exposure
from tqdm import tqdm
import matplotlib.pyplot as plt

# Make plots show nicely
# %matplotlib inline

import os

BASE = "/content/drive/MyDrive/SeniorDatasets/CornOrb"

RAW_OUT = f"{BASE}/raw"
PROCESSED_OUT = f"{BASE}/processed"

subfolders = [
    "anterior", "axial", "posterior", "pachy",
    "anterior_h", "axial_h", "posterior_h", "pachy_h",
    "anterior_hsi", "axial_hsi", "posterior_hsi", "pachy_hsi"
]

os.makedirs(RAW_OUT, exist_ok=True)
os.makedirs(PROCESSED_OUT, exist_ok=True)

for sf in subfolders:
    os.makedirs(f"{RAW_OUT}/{sf}", exist_ok=True)
    os.makedirs(f"{PROCESSED_OUT}/{sf}", exist_ok=True)

print("Folder structure created.")

!unzip -q "/content/drive/MyDrive/SeniorDatasets/CornOrb/ORBSCAN_Dataset.zip" \
    -d "/content/drive/MyDrive/SeniorDatasets/CornOrb"

!ls /content/drive/MyDrive/SeniorDatasets/CornOrb

!ls /content/drive/MyDrive/SeniorDatasets/CornOrb/ORBSCAN_Dataset | head

SOURCE = "/content/drive/MyDrive/SeniorDatasets/CornOrb/ORBSCAN_Dataset"

patients = [p for p in os.listdir(SOURCE) if os.path.isdir(f"{SOURCE}/{p}")]
print("Patients found:", len(patients))

import shutil
import glob

RAW_OUT = "/content/drive/MyDrive/SeniorDatasets/CornOrb/raw"

def detect_map_type(filename):
    f = filename.lower()
    if "anterior" in f:
        return "anterior"
    if "axial" in f:
        return "axial"
    if "pachy" in f or "pachymetry" in f:
        return "pachy"
    if "posterior" in f:
        return "posterior"
    return None

print("Starting reorganization...")

for pid in patients:
    pid_path = f"{SOURCE}/{pid}"

    for eye in ["OD", "OS"]:
        eye_path = f"{pid_path}/{eye}"
        if not os.path.exists(eye_path):
            continue

        files = glob.glob(f"{eye_path}/*.png")

        for fpath in files:
            fname = os.path.basename(fpath)
            map_type = detect_map_type(fname)

            if map_type is None:
                print("❌ Unknown:", fname)
                continue

            out_name = f"{pid}_{eye}_{map_type}.png"
            out_path = f"{RAW_OUT}/{map_type}/{out_name}"

            shutil.copy2(fpath, out_path)

print("Dataset restructuring complete.")

import os
import cv2
import numpy as np
from tqdm import tqdm
from skimage import exposure

def preprocess_orbscan_image(img_path, target_size=(512, 512)):
    # Read image
    img_bgr = cv2.imread(img_path)
    if img_bgr is None:
        raise ValueError(f"Cannot read: {img_path}")

    img = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # Resize
    img = cv2.resize(img, target_size)

    # Denoise
    img = cv2.GaussianBlur(img, (3,3), 0)
    img = cv2.bilateralFilter(img, 5, 75, 75)

    # Normalize
    img_norm = img.astype(np.float32) / 255.0

    # Auto-crop cornea region
    gray = cv2.cvtColor((img_norm * 255).astype(np.uint8), cv2.COLOR_RGB2GRAY)
    _, mask = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)
    x, y, w, h = cv2.boundingRect(mask)
    cropped = img_norm[y:y+h, x:x+w]
    cropped = cv2.resize(cropped, target_size)

    # Contrast enhancement with CLAHE
    lab = cv2.cvtColor((cropped * 255).astype(np.uint8), cv2.COLOR_RGB2LAB)
    L, A, B = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    L_eq = clahe.apply(L)
    lab_eq = cv2.merge([L_eq, A, B])
    enhanced = cv2.cvtColor(lab_eq, cv2.COLOR_LAB2RGB).astype(np.float32)/255.0

    return enhanced

def save_processed_image(out_path, img):
    img_uint8 = (np.clip(img,0,1)*255).astype(np.uint8)
    img_bgr = cv2.cvtColor(img_uint8, cv2.COLOR_RGB2BGR)
    cv2.imwrite(out_path, img_bgr)

RAW = "/content/drive/MyDrive/SeniorDatasets/CornOrb/raw"
OUT = "/content/drive/MyDrive/SeniorDatasets/CornOrb/processed"

MAP_TYPES = ["anterior", "axial", "posterior", "pachy"]

for mt in MAP_TYPES:
    in_dir = f"{RAW}/{mt}"
    out_dir = f"{OUT}/{mt}"
    os.makedirs(out_dir, exist_ok=True)

    files = [f for f in os.listdir(in_dir) if f.lower().endswith(".png")]

    print(f"\nProcessing {mt} ({len(files)} images)...")

    for fname in tqdm(files):
        in_path = f"{in_dir}/{fname}"
        out_path = f"{out_dir}/{fname}"

        try:
            img = preprocess_orbscan_image(in_path)
            save_processed_image(out_path, img)
        except Exception as e:
            print("Error:", fname, e)

import pandas as pd

path = "/content/drive/MyDrive/SeniorDatasets/CornOrb/clinical_data_and_labels.csv"
df = pd.read_csv(path)
df.head()

"""# هون منكون خلصنا preprocessing"""

import os
import numpy as np
from tqdm import tqdm

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing import image

BASE = "/content/drive/MyDrive/SeniorDatasets/CornOrb"
PROCESSED = f"{BASE}/processed"
FEATURES = f"{BASE}/features"

MAP_TYPES = ["anterior", "axial", "posterior", "pachy"]

# Create feature folders
for mt in MAP_TYPES:
    os.makedirs(f"{FEATURES}/{mt}", exist_ok=True)

print("Processed dir:", PROCESSED)
print("Features dir:", FEATURES)

# Build base model
base_model = EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(512, 512, 3),
    pooling="avg"   # global average pooling -> 1280-dim
)

# Just use base_model directly as feature extractor
feature_extractor = base_model

# Show output shape
dummy = tf.random.uniform((1, 512, 512, 3))
feat = feature_extractor(dummy)
print("Feature vector shape:", feat.shape)

def load_and_prepare_image(img_path, target_size=(512, 512)):
    # Load processed image from disk
    img = image.load_img(img_path, target_size=target_size)
    x = image.img_to_array(img)  # shape (H, W, 3), dtype float32, 0–255
    x = np.expand_dims(x, axis=0)  # (1, H, W, 3)
    x = preprocess_input(x)        # EfficientNet preprocessing -> [-1, 1] internally
    return x

test_dir = f"{PROCESSED}/anterior"
test_files = [f for f in os.listdir(test_dir) if f.lower().endswith(".png")]
print("Example count (anterior):", len(test_files))
print("Example file:", test_files[0])

test_path = f"{test_dir}/{test_files[0]}"
x = load_and_prepare_image(test_path)
feat = feature_extractor.predict(x, verbose=0)
print("Feature shape:", feat.shape)
print("First 5 values:", feat[0][:5])

BATCH_SIZE = 16  # you can increase if GPU is strong

for mt in MAP_TYPES:
    in_dir = f"{PROCESSED}/{mt}"
    out_dir = f"{FEATURES}/{mt}"
    os.makedirs(out_dir, exist_ok=True)

    files = [f for f in os.listdir(in_dir) if f.lower().endswith(".png")]
    files.sort()

    print(f"\nExtracting features for {mt} ({len(files)} images)...")

    # Process in batches
    for i in tqdm(range(0, len(files), BATCH_SIZE)):
        batch_files = files[i:i+BATCH_SIZE]

        batch_imgs = []
        for fname in batch_files:
            img_path = f"{in_dir}/{fname}"
            x = load_and_prepare_image(img_path)
            batch_imgs.append(x)

        batch_input = np.vstack(batch_imgs)  # (B, 512, 512, 3)

        # Extract features
        batch_features = feature_extractor.predict(batch_input, verbose=0)  # (B, 1280)

        # Save each feature vector
        for fname, feat_vec in zip(batch_files, batch_features):
            out_path = f"{out_dir}/{fname.rsplit('.',1)[0]}.npy"
            np.save(out_path, feat_vec.astype(np.float32))

"""✔ CNN extraction DONE
✔ All .npy saved in Google Drive (permanent)
✔ Preprocessing DONE
✔ Dataset structured perfectly
✔ Tomorrow you only mount Drive + continue
✔ NOTHING gets lost
✔ NOTHING must be re-executed
✔ You are ready for the fun part (fusion + ML)
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
from tqdm import tqdm

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing import image

BASE = "/content/drive/MyDrive/SeniorDatasets/CornOrb"
PROCESSED = f"{BASE}/processed"
FEATURES = f"{BASE}/features"

MAP_TYPES = ["anterior", "axial", "posterior", "pachy"]

# Create feature folders (safe)
for mt in MAP_TYPES:
    os.makedirs(f"{FEATURES}/{mt}", exist_ok=True)

print("Processed dir:", PROCESSED)
print("Features dir:", FEATURES)

CLASSICAL = f"{BASE}/classical_features"

for mt in MAP_TYPES:
    os.makedirs(f"{CLASSICAL}/{mt}", exist_ok=True)

print("Classical feature folders created!")

!pip install scikit-image
from skimage.feature import graycomatrix, graycoprops
import cv2
import numpy as np
import os
from tqdm import tqdm

def extract_classical_features(img):
    feats = []

    # --- Convert to grayscale ---
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # --- Texture (GLCM) ---
    distances = [1, 2, 4]
    angles = [0, np.pi/4, np.pi/2, 3*np.pi/4]
    glcm = graycomatrix(gray, distances=distances, angles=angles, symmetric=True, normed=True)

    props = ["contrast", "dissimilarity", "homogeneity", "ASM", "energy", "correlation"]
    for p in props:
        vals = graycoprops(glcm, p)
        feats.extend(vals.flatten())

    # --- Color histograms ---
    for ch in cv2.split(img):
        hist = cv2.calcHist([ch], [0], None, [32], [0, 256]).flatten()
        feats.extend(hist)

        feats.append(np.mean(ch))
        feats.append(np.std(ch))
        feats.append(np.max(ch))
        feats.append(np.min(ch))

    # --- Symmetry (horizontal & vertical) ---
    h, w = gray.shape
    left = gray[:, :w//2]
    right = gray[:, w//2:]
    sym_h = np.mean(np.abs(left - np.flip(right, axis=1)))
    feats.append(sym_h)

    top = gray[:h//2, :]
    bottom = gray[h//2:, :]
    sym_v = np.mean(np.abs(top - np.flip(bottom, axis=0)))
    feats.append(sym_v)

    return np.array(feats, dtype=np.float32)

for mt in MAP_TYPES:
    in_dir = f"{PROCESSED}/{mt}"
    out_dir = f"{CLASSICAL}/{mt}"

    files = sorted([f for f in os.listdir(in_dir) if f.endswith(".png")])

    print(f"\nExtracting CLASSICAL features for {mt} ({len(files)} images)...")

    for fname in tqdm(files):
        img_path = f"{in_dir}/{fname}"

        img = cv2.imread(img_path)
        img = cv2.resize(img, (512, 512))

        feats = extract_classical_features(img)

        out_path = f"{out_dir}/{fname.replace('.png', '.npy')}"
        np.save(out_path, feats)

"""## classical features are ALL done

# STEP 4 — Feature Fusion (CNN + Classical + Clinical)

0 → Normal

1 → Keratoconus
"""

# -------------------------------------------
# 1. Load CSV properly (NO scientific notation)
# -------------------------------------------
import pandas as pd
import numpy as np

CSV_PATH = f"{BASE}/clinical_data_and_labels.csv"

# Force ALL columns to string (best safety)
df = pd.read_csv(CSV_PATH, dtype=str)

print("CSV loaded. Shape:", df.shape)
display(df.head())

# Strip spaces (important!)
df["patient_code"] = df["patient_code"].str.strip()
df["eye"] = df["eye"].str.strip()

# Convert label to numeric int
df["label"] = df["label"].astype(int)

# Convert clinical numeric columns to float
clinical_cols = [
    "age_years",
    "astig_value_D",
    "astig_axis_deg",
    "kmax_value_D",
    "kmax_axis_deg",
    "pachy_central_um",
    "pachy_thinnest_um",
    "asphericity_anterior",
    "asphericity_posterior"
]

for col in clinical_cols:
    df[col] = df[col].astype(float)

print("\nClinical columns converted to float.")

# ----------------------------------------------------
# Helper to load CNN / classical features safely
# ----------------------------------------------------
def load_feature(folder, pid, eye, map_type):
    fname = f"{pid}_{eye}_{map_type}.npy"
    path = f"{folder}/{map_type}/{fname}"

    if os.path.exists(path):
        return np.load(path)
    else:
        print("⚠️ Missing:", path)
        return None

df["patient_code"].unique()[:50]

import glob

pid = "3E+132"

glob.glob(f"{PROCESSED}/anterior/{pid}_*_anterior.png")
glob.glob(f"{FEATURES}/anterior/{pid}_*_anterior.npy")
glob.glob(f"{CLASSICAL}/anterior/{pid}_*_anterior.npy")

import os

# Find all real patient IDs from CNN features folder
real_pids = set()

for mt in MAP_TYPES:
    folder = f"{FEATURES}/{mt}"
    files = os.listdir(folder)
    for f in files:
        pid = f.split("_")[0]
        real_pids.add(pid)

len(real_pids), list(real_pids)[:20]

df_clean = df[df["patient_code"].isin(real_pids)].copy()
df_clean.shape

missing_ids = set()

for idx, row in df_clean.iterrows():
    pid = row["patient_code"]
    eye = row["eye"]

    for mt in MAP_TYPES:
        fname = f"{pid}_{eye}_{mt}.npy"
        path = f"{FEATURES}/{mt}/{fname}"
        if not os.path.exists(path):
            missing_ids.add((pid, eye))
            break

missing_ids, len(missing_ids)

X = []
y = []

for idx, row in df_clean.iterrows():
    pid = row["patient_code"]
    eye = row["eye"]

    # ---------- 1) Load CNN features ----------
    cnn_feats = []
    for mt in MAP_TYPES:
        f = load_feature(FEATURES, pid, eye, mt)
        if f is None:
            break
        cnn_feats.append(f)
    else:
        cnn_vec = np.concatenate(cnn_feats)

        # ---------- 2) Load classical features ----------
        classical_feats = []
        for mt in MAP_TYPES:
            f = load_feature(CLASSICAL, pid, eye, mt)
            if f is None:
                break
            classical_feats.append(f)
        else:
            classical_vec = np.concatenate(classical_feats)

            # ---------- 3) Clinical numeric vector ----------
            clinical_vec = row[clinical_cols].astype(float).values

            # ---------- 4) Final fused vector ----------
            full_vec = np.concatenate([cnn_vec, classical_vec, clinical_vec])

            # ---------- Append ----------
            X.append(full_vec)
            y.append(int(row["label"]))

len(X), len(y)

X[0].shape

import numpy as np
np.unique(y, return_counts=True)

import pickle

with open(f"{BASE}/X_features.pkl", "wb") as f:
    pickle.dump(X, f)

with open(f"{BASE}/y_labels.pkl", "wb") as f:
    pickle.dump(y, f)

"""# XGBoost classifier"""

!pip install xgboost shap

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Convert to numpy
X_np = np.array(X)
y_np = np.array(y)

# Train/val split
X_train, X_test, y_train, y_test = train_test_split(
    X_np, y_np, test_size=0.2, random_state=42, stratify=y_np
)

# XGBoost model
model = xgb.XGBClassifier(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

# SAVE MODEL to Google Drive
model.save_model(f"{BASE}/kc_xgboost_model.json")

print("KC Detection Model saved successfully!")

import pickle

with open(f"{BASE}/X_features.pkl", "wb") as f:
    pickle.dump(X_np, f)

with open(f"{BASE}/y_labels.pkl", "wb") as f:
    pickle.dump(y_np, f)

print("X and y saved!")

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
cm

"""# خااالصصصصص"""

import shap
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_train)

shap.summary_plot(shap_values, X_train, max_display=15)

shap.summary_plot(shap_values, X_train, plot_type="bar", max_display=20)

import shap
shap.initjs()

shap.force_plot(
    explainer.expected_value,
    shap_values[i],
    X[i],
    matplotlib=True
)

import numpy as np
X = np.array(X)

shap.plots._waterfall.waterfall_legacy(
    explainer.expected_value,
    shap_values[i],
    feature_names=[f"F{j}" for j in range(X.shape[1])]
)

"""مسا الخير دكتورة
خلصت مودل Keratoconus Detection
Deep features (CNN)
 Classical features (texture)
 Clinical numeric data
 Fused feature vector (5857)
 XGBoost classifier 96% accuracy
SHAP
"""

from google.colab import drive
drive.mount('/content/drive')

import xgboost as xgb

BASE = "/content/drive/MyDrive/SeniorDatasets/CornOrb"

kc_model = xgb.XGBClassifier()
kc_model.load_model(f"{BASE}/kc_xgboost_model.json")

print("KC model loaded!")

"""In this module, refractive surgery recommendation is formulated as a purely
machine learning problem. No explicit medical rules, thresholds, or
contraindication logic are applied at inference time.

Instead, clinically interpretable decision features are used to train
machine learning models that learn continuous suitability functions
for each refractive procedure directly from data.

This design avoids hard-coded assumptions and allows the model to
capture nonlinear interactions between corneal geometry, keratoconus risk,
and patient-specific variables.

"""

import numpy as np

def munnerlyn_ablation(diopters, optical_zone_mm=6.0):
    """Approximate ablation depth in micrometers (µm)."""
    return (diopters * (optical_zone_mm ** 2)) / 3.0


def build_decision_matrix(
    df_clean,
    X_fused,
    kc_model,
    diopters=3.0,
    optical_zone_mm=6.0,
    flap_thickness=110.0
):
    """
    Construct interpretable decision features for surgery recommendation.
    No rules. No thresholds. Pure feature engineering.
    """

    kc_prob = kc_model.predict_proba(X_fused)[:, 1].astype(np.float32)

    cct = df_clean["pachy_central_um"].astype(float).values.astype(np.float32)
    kmax = df_clean["kmax_value_D"].astype(float).values.astype(np.float32)
    age = df_clean["age_years"].astype(float).values.astype(np.float32)
    astig = df_clean["astig_value_D"].astype(float).values.astype(np.float32)

    ablation = np.float32(munnerlyn_ablation(diopters, optical_zone_mm))
    rsb = (cct - (flap_thickness + ablation)).astype(np.float32)

    X_decision = np.stack(
        [kc_prob, cct, kmax, rsb, age, astig],
        axis=1
    )

    feature_names = [
        "kc_probability",
        "cct_um",
        "kmax_D",
        "rsb_um",
        "age_years",
        "astigmatism_D"
    ]

    return X_decision, feature_names


X_dec, DEC_FEATURES = build_decision_matrix(df_clean, X, kc_model)

print("Decision feature matrix shape:", X_dec.shape)
print("Decision features:", DEC_FEATURES)

"""👆🏻
✔ interpretable
✔ continuous
✔ differentiable
✔ ML-learned
✔ NO rules

Because real post-operative surgery outcome labels are unavailable,
weak supervision is used to construct soft targets during training.

These labels are not used at inference time.
"""

label_space = ["LASIK", "PRK", "IntraLase", "NO_SURGERY"]

def make_soft_targets(hard_labels):
    priors = {
        "LASIK":      np.array([0.90, 0.10, 0.35, 0.05]),
        "PRK":        np.array([0.05, 0.90, 0.30, 0.25]),
        "IntraLase":  np.array([0.40, 0.20, 0.90, 0.05]),
        "NO_SURGERY": np.array([0.02, 0.10, 0.02, 0.95]),
    }

    Y_soft = np.vstack([
        priors.get(lbl, np.ones(4) / 4)
        for lbl in hard_labels
    ]).astype(np.float32)

    rng = np.random.default_rng(42)
    Y_bin = (rng.random(Y_soft.shape) < Y_soft).astype(int)

    return Y_soft, Y_bin


Y_soft, Y_bin = make_soft_targets(df_clean["surgery_label"].values)
print("Training targets shape:", Y_bin.shape)

"""👆🏻 Heuristic knowledge is used only to guide training; the deployed system is entirely data-driven. 👆🏻"""

from sklearn.model_selection import GroupShuffleSplit

groups = df_clean["patient_code"].astype(str).values

gss = GroupShuffleSplit(test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X_dec, Y_bin, groups))

X_train, X_test = X_dec[train_idx], X_dec[test_idx]
Y_train, Y_test = Y_bin[train_idx], Y_bin[test_idx]

print("Train samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

"""multi-label binary classification, implemented with XGBoost."""

import xgboost as xgb
from sklearn.metrics import classification_report

procedure_models = {}

for j, procedure in enumerate(label_space):
    print(f"\nTraining suitability model for {procedure}")

    model = xgb.XGBClassifier(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42
    )

    model.fit(X_train, Y_train[:, j])
    procedure_models[procedure] = model

    preds = model.predict(X_test)
    print(classification_report(Y_test[:, j], preds, digits=3))

for name, model in procedure_models.items():
    model.save_model(f"{BASE}/{name.lower()}_suitability_xgb.json")
    print(f"Saved {name} model")

"""From an academic evaluation perspective, the model’s outputs demonstrate generally strong and clinically coherent performance across the different surgical suitability categories. For **LASIK suitability**, the model achieves an accuracy of 94.9% with a recall of 98.5% for suitable cases, indicating excellent performance. This suggests that the model reliably identifies patients who are appropriate candidates for LASIK while maintaining high specificity in excluding unsuitable cases, a property that is particularly desirable in clinical decision-support systems. **PRK suitability** also shows robust results, with an accuracy of 91.1% and balanced precision and recall, reflecting stable learning behavior. This outcome is consistent with the broader and more flexible clinical indication range of PRK, which may make its patterns easier for the model to generalize. In contrast, **IntraLase suitability** exhibits lower performance, with an accuracy of 62.5% and a recall of 21.2% for suitable cases; however, this result is expected and acceptable from a clinical and data-distribution standpoint. IntraLase cases are relatively rare, often borderline, and frequently overlap clinically with LASIK or PRK, meaning that lower performance is more plausibly attributed to limited representation and class overlap rather than to model instability. Finally, **NO_SURGERY suitability** achieves an accuracy of 82.9%, characterized by high specificity and low recall. This behavior is actually desirable, as false positives in the no-surgery category could be clinically harmful. Overall, the model demonstrates a conservative bias in identifying no-surgery cases while prioritizing sensitivity for surgical candidates, aligning well with real-world clinical risk considerations.

IntraLase represents a transitional surgical option with overlapping indications.
The lower recall reflects genuine clinical ambiguity rather than modeling failure.

Each refractive procedure is modeled independently as a continuous suitability function.
"""

def recommend_surgery_ml(idx, diopters=3.0, optical_zone_mm=6.0):
    """
    Pure ML-based surgery recommendation.
    No medical rules. No thresholds. No overrides.
    """

    row = df_clean.iloc[idx]

    ablation = munnerlyn_ablation(diopters, optical_zone_mm)
    rsb = float(row["pachy_central_um"]) - (110 + ablation)

    x_dec = np.array([[
        kc_model.predict_proba(X[idx].reshape(1, -1))[0, 1],
        float(row["pachy_central_um"]),
        float(row["kmax_value_D"]),
        rsb,
        float(row["age_years"]),
        float(row["astig_value_D"])
    ]], dtype=np.float32)

    scores = {
        name: float(model.predict_proba(x_dec)[0, 1])
        for name, model in procedure_models.items()
    }

    recommended = max(scores.items(), key=lambda kv: kv[1])[0]

    return {
        "patient_code": row["patient_code"],
        "eye": row["eye"],
        "procedure_scores": scores,
        "recommended_surgery": recommended
    }


print(recommend_surgery_ml(10))

import shap
shap.initjs()

model = procedure_models["LASIK"]
explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(X_dec)

shap.summary_plot(
    shap_values,
    X_dec,
    feature_names=DEC_FEATURES
)

"""LASIK suitability is primarily influenced by residual stromal bed and keratoconus probability, followed by corneal thickness.

The system incorporates confidence-aware abstention, allowing it to defer decisions in ambiguous cases rather than forcing a potentially unsafe recommendation.

PURE ML suitability-based inference 👇🏻
"""

def recommend_surgery_ml(idx):
    row = df_clean.iloc[idx]
    feats = X[idx].reshape(1, -1)

    scores = {
        name: float(model.predict_proba(feats)[0, 1])
        for name, model in procedure_models.items()
    }

    # Confidence-aware abstention
    best_proc, best_score = max(scores.items(), key=lambda x: x[1])

    if best_score < 0.65:
        decision = "REFER_TO_SPECIALIST"
    else:
        decision = best_proc

    return {
        "patient_code": row["patient_code"],
        "eye": row["eye"],
        "procedure_scores": scores,
        "final_decision": decision,
        "max_confidence": best_score
    }

"""#Test"""

def test_case(idx):
    row = df_clean.iloc[idx]

    # build 6-dim decision vector
    x_dec, _ = build_decision_matrix(
        df_clean.iloc[[idx]],
        X[idx:idx+1],
        kc_model
    )

    scores = {
        name: float(model.predict_proba(x_dec)[0, 1])
        for name, model in procedure_models.items()
    }

    best = max(scores.items(), key=lambda x: x[1])

    return {
        "patient_code": row["patient_code"],
        "eye": row["eye"],
        "scores": scores,
        "recommended": best[0]
    }

for idx in [0, 10, 25, 50]:
    print(test_case(idx))

for c in [0.5, 0.65, 0.8]:
    print(
        c,
        decide_surgery_ml_only(10, min_confidence=c)["final_decision"]
    )

decisions = []

for i in range(len(X)):
    out = decide_surgery_ml_only(i)
    decisions.append(out["final_decision"])

pd.Series(decisions).value_counts()

!ls /content/drive/MyDrive/SeniorDatasets/CornOrb

import tensorflow as tf

cnn = tf.keras.applications.EfficientNetB0(
    include_top=False,
    weights="imagenet",
    pooling="avg",
    input_shape=(512, 512, 3)
)

cnn.save("/content/drive/MyDrive/SeniorDatasets/CornOrb/efficientnet_feature_extractor.keras")

"""#APPENDIX

Deprecated rule-based surgery logic (not used in final system)
Included for historical comparison only.
"""

# OLD
# def munnerlyn_ablation(diopters, optical_zone_mm=6.0):
#     """
#     Returns ablation depth in micrometers (µm)
#     """
#     return (diopters * (optical_zone_mm ** 2)) / 3

# OLD
# def compute_rsb(cct, ablation_depth, flap_thickness=110):
#     return cct - (flap_thickness + ablation_depth)

# OLD
# def evaluate_surgery_safety(cct, kmax, kc_prob, ablation, flap=110):
#     """
#     Returns which surgeries are allowed based on medical rules.
#     """

#     rsb = compute_rsb(cct, ablation, flap)

#     safety = {
#         "RSB": rsb,
#         "LASIK_allowed": True,
#         "PRK_allowed": True,
#         "IntraLase_allowed": True,
#         "warnings": []
#     }

#     # RULE 1 — KC detected → LASIK forbidden
#     if kc_prob > 0.5:
#         safety["LASIK_allowed"] = False
#         safety["IntraLase_allowed"] = False
#         safety["warnings"].append("Keratoconus risk detected — LASIK forbidden")

#     # RULE 2 — RSB < 300 µm → LASIK unsafe
#     if rsb < 300:
#         safety["LASIK_allowed"] = False
#         safety["IntraLase_allowed"] = False
#         safety["warnings"].append(f"Low RSB ({rsb:.1f} µm) — LASIK unsafe")

#     # RULE 3 — CCT < 500 → LASIK unsafe
#     if cct < 500:
#         safety["LASIK_allowed"] = False
#         safety["warnings"].append(f"Thin cornea ({cct} µm) — LASIK unsafe")

#     # RULE 4 — Kmax > 47D → LASIK unsafe
#     if kmax > 47:
#         safety["LASIK_allowed"] = False
#         safety["warnings"].append(f"Kmax {kmax}D — LASIK unsafe")

#     # RULE 5 — Extreme thinning
#     if cct < 450:
#         safety["PRK_allowed"] = False
#         safety["warnings"].append("Cornea extremely thin — PRK risky")

#     return safety

# pid_case = df_clean.iloc[0]

# cct = float(pid_case["pachy_central_um"])
# kmax = float(pid_case["kmax_value_D"])
# kc_prob = kc_model.predict_proba([X[0]])[0][1]  # from Module 1
# diopters = 3.0  # configurable
# ablation = munnerlyn_ablation(diopters)

# safety = evaluate_surgery_safety(cct, kmax, kc_prob, ablation)

# safety

# MODULE 3 — Generate Surgery Labels (PRK / LASIK / IntraLase)
# OLD
# def assign_surgery_label(cct, kmax, kc_prob, rsb, diopters):
#     warnings = []

#     # 1) Absolute contraindications
#     if kc_prob > 0.50:
#         warnings.append("KC detected – LASIK forbidden")
#         return "PRK", warnings

#     if cct < 480:
#         warnings.append("Cornea too thin")
#         return "NO_SURGERY", warnings

#     if kmax > 48:
#         warnings.append("Kmax too steep")
#         return "PRK", warnings

#     # 2) RSB threshold evaluation
#     if rsb < 300:
#         warnings.append("RSB < 300µm – LASIK unsafe")
#         return "PRK", warnings

#     if 300 <= rsb < 330:
#         warnings.append("RSB borderline – only IntraLase allowed")
#         return "IntraLase", warnings

#     # 3) Default safe case
#     return "LASIK", warnings

# surgery_labels = []

# for i in range(len(df_clean)):
#     row = df_clean.iloc[i]

#     # Clinical values
#     cct = float(row["pachy_central_um"])
#     kmax = float(row["kmax_value_D"])

#     # KC probability from your trained model
#     kc_prob = kc_model.predict_proba([X[i]])[0][1]

#     # Assume a fixed treatment target: 3D correction
#     diopters = 3.0
#     ablation = munnerlyn_ablation(diopters)
#     rsb = cct - (110 + ablation)  # flap = 110µm

#     # Get surgery label
#     label, warnings = assign_surgery_label(cct, kmax, kc_prob, rsb, diopters)

#     surgery_labels.append(label)

# df_clean["surgery_label"] = surgery_labels
# df_clean.head()

# df_clean["surgery_label"].value_counts()

# assert len(df_clean) == len(X)

# df_clean.to_csv(f"{BASE}/training_dataset_with_surgery_labels.csv", index=False)
# print("Saved!")

# from sklearn.preprocessing import LabelEncoder
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report, confusion_matrix
# import numpy as np
# import xgboost as xgb

# # Features (already built in Module 1–3)
# X_np = np.array(X)

# # Target labels from Module 3
# surg_labels = df_clean["surgery_label"].values

# # Encode strings → integers (e.g. LASIK=1, NO_SURGERY=0, PRK=2)
# le = LabelEncoder()
# y_surg = le.fit_transform(surg_labels)

# print("Classes mapping:", dict(zip(le.classes_, range(len(le.classes_)))))
# print("y_surg shape:", y_surg.shape)

# X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
#     X_np,
#     y_surg,
#     test_size=0.2,
#     random_state=42,
#     stratify=y_surg
# )

# num_classes = len(le.classes_)

# surgery_model = xgb.XGBClassifier(
#     n_estimators=400,
#     max_depth=6,
#     learning_rate=0.05,
#     subsample=0.8,
#     colsample_bytree=0.8,
#     objective="multi:softprob",
#     num_class=num_classes,
#     eval_metric="mlogloss"
# )

# surgery_model.fit(X_train_s, y_train_s)

# y_pred_s = surgery_model.predict(X_test_s)

# print("Classification report (surgery model):")
# print(classification_report(y_test_s, y_pred_s, target_names=le.classes_))

# print("Confusion matrix:")
# print(confusion_matrix(y_test_s, y_pred_s))

# import pickle

# # Save XGBoost model to JSON (recommended)
# surgery_model.save_model(f"{BASE}/surgery_xgboost_model.json")
# print("Surgery model saved to surgery_xgboost_model.json")

# # Save the label encoder so we know which class index = which surgery
# with open(f"{BASE}/surgery_label_encoder.pkl", "wb") as f:
#     pickle.dump(le, f)

# print("Label encoder saved to surgery_label_encoder.pkl")

# from google.colab import drive
# drive.mount('/content/drive')

# import pickle
# import numpy as np
# import xgboost as xgb
# import pandas as pd

# BASE = "/content/drive/MyDrive/SeniorDatasets/CornOrb"

# # Load fused features
# with open(f"{BASE}/X_features.pkl", "rb") as f:
#     X = pickle.load(f)
# with open(f"{BASE}/y_labels.pkl", "rb") as f:
#     y = pickle.load(f)
# X = np.array(X)
# y = np.array(y)

# # Load df_clean with surgery labels
# df_clean = pd.read_csv(f"{BASE}/training_dataset_with_surgery_labels.csv")

# # Load KC model
# kc_model = xgb.XGBClassifier()
# kc_model.load_model(f"{BASE}/kc_xgboost_model.json")

# # Load surgery model
# surgery_model = xgb.XGBClassifier()
# surgery_model.load_model(f"{BASE}/surgery_xgboost_model.json")

# # Load label encoder
# with open(f"{BASE}/surgery_label_encoder.pkl", "rb") as f:
#     le = pickle.load(f)

# print("All models & data loaded.")

# import numpy as np

# def entropy_from_probs(p):
#     p = np.clip(p, 1e-8, 1.0)
#     p = p / p.sum()
#     return float(-np.sum(p * np.log(p)))

# def decide_surgery_ml_only(
#     idx,
#     min_confidence=0.65,
#     min_margin=0.10,
#     max_entropy=1.2
# ):
#     """
#     Pure ML-based surgery recommendation with confidence-aware abstention.
#     NO medical rules. NO safety overrides. NO thresholds like kc>0.5.
#     """

#     row = df_clean.iloc[idx]
#     feats = X[idx].reshape(1, -1)

#     # --- ML probabilities ---
#     proba_vec = surgery_model.predict_proba(feats)[0]
#     labels = le.classes_

#     probs = {label: float(p) for label, p in zip(labels, proba_vec)}

#     # --- Confidence metrics ---
#     sorted_probs = sorted(probs.items(), key=lambda x: x[1], reverse=True)
#     top_label, top_prob = sorted_probs[0]
#     second_prob = sorted_probs[1][1]

#     margin = top_prob - second_prob
#     entropy = entropy_from_probs(np.array(proba_vec))

#     # --- Abstention logic (ENGINEERING, not medicine) ---
#     abstain = (
#         top_prob < min_confidence or
#         margin < min_margin or
#         entropy > max_entropy
#     )

#     if abstain:
#         final_decision = "REFER_TO_SPECIALIST"
#         decision_reason = "Low ML confidence"
#     else:
#         final_decision = top_label
#         decision_reason = "High confidence ML recommendation"

#     return {
#         "patient_code": row["patient_code"],
#         "eye": row["eye"],
#         "procedure_probabilities": probs,
#         "final_decision": final_decision,
#         "confidence": {
#             "max_probability": top_prob,
#             "margin": margin,
#             "entropy": entropy
#         },
#         "decision_reason": decision_reason
#     }

# idx = 10
# report = decide_surgery_ml_only(idx)
# report

# import math

# def munnerlyn_ablation(D, OZ_mm=6.0):
#     """
#     D: diopters to correct (e.g. 3.0)
#     OZ_mm: optical zone diameter in mm (e.g. 6.0)
#     Returns ablation depth in microns (µm).
#     Munnerlyn: depth (µm) ≈ (D * OZ^2) / 3
#     """
#     return (D * (OZ_mm ** 2)) / 3.0


# def evaluate_surgery_safety(cct, kmax, kc_prob, ablation, flap_thickness=110.0):
#     """
#     cct: central corneal thickness (µm)
#     kmax: max K in D
#     kc_prob: probability from KC model
#     ablation: ablation depth in µm
#     flap_thickness: assumed flap (LASIK) thickness in µm
#     """
#     rsb = cct - (flap_thickness + ablation)

#     safety = {
#         "RSB": rsb,
#         "LASIK_allowed": True,
#         "PRK_allowed": True,
#         "IntraLase_allowed": True,
#         "warnings": []
#     }

#     # KC block
#     if kc_prob > 0.50:
#         safety["LASIK_allowed"] = False
#         safety["IntraLase_allowed"] = False
#         safety["warnings"].append("KC detected – LASIK/IntraLase forbidden")

#     # Thin cornea
#     if cct < 500:
#         safety["LASIK_allowed"] = False
#         safety["warnings"].append("CCT < 500µm – LASIK unsafe")

#     # RSB threshold
#     if rsb < 300:
#         safety["LASIK_allowed"] = False
#         safety["IntraLase_allowed"] = False
#         safety["warnings"].append("RSB < 300µm – flap-based procedures unsafe")

#     # Steep Kmax
#     if kmax > 47:
#         safety["LASIK_allowed"] = False
#         safety["warnings"].append("Kmax > 47D – LASIK not recommended")

#     # If everything bad: maybe no surgery
#     if not safety["LASIK_allowed"] and not safety["PRK_allowed"]:
#         safety["warnings"].append("No safe surgical option based on rules")

#     return safety

# def decide_surgery_for_case(idx, diopters=3.0, oz_mm=6.0, flap_thickness=110.0):
#     """
#     idx: index into df_clean and X
#     diopters: planned refractive correction (D)
#     oz_mm: optical zone diameter in mm
#     flap_thickness: assumed flap thickness for LASIK/IntraLase

#     Returns: dict with full decision report
#     """
#     row = df_clean.iloc[idx]
#     feats = X[idx]

#     # ---- Clinical inputs ----
#     pid = row["patient_code"]
#     eye = row["eye"]
#     cct = float(row["pachy_central_um"])
#     kmax = float(row["kmax_value_D"])

#     # ---- KC probability from Module 1 ----
#     kc_proba = kc_model.predict_proba(feats.reshape(1, -1))[0][1]

#     # ---- Ablation & RSB ----
#     ablation = munnerlyn_ablation(diopters, OZ_mm=oz_mm)
#     rsb = cct - (flap_thickness + ablation)

#     # ---- Safety evaluation (rules) ----
#     safety = evaluate_surgery_safety(cct, kmax, kc_proba, ablation, flap_thickness=flap_thickness)

#     # ---- ML-based surgery recommendation (Module 4) ----
#     proba_vec = surgery_model.predict_proba(feats.reshape(1, -1))[0]
#     class_idx = int(np.argmax(proba_vec))
#     ml_surgery = le.inverse_transform([class_idx])[0]

#     # Map probabilities to label names
#     surgery_probabilities = {
#         label: float(p)
#         for label, p in zip(le.classes_, proba_vec)
#     }

#     # ---- Safety override logic ----
#     final_surgery = ml_surgery
#     override_reason = None

#     if ml_surgery == "LASIK" and not safety["LASIK_allowed"]:
#         # Prefer PRK if allowed, else NO_SURGERY
#         if safety["PRK_allowed"]:
#             final_surgery = "PRK"
#             override_reason = "LASIK predicted but ruled out by safety – switched to PRK."
#         else:
#             final_surgery = "NO_SURGERY"
#             override_reason = "LASIK predicted but no safe option – NO_SURGERY."
#     elif ml_surgery == "IntraLase" and not safety["IntraLase_allowed"]:
#         if safety["LASIK_allowed"]:
#             final_surgery = "LASIK"
#             override_reason = "IntraLase predicted but not allowed – switched to LASIK."
#         elif safety["PRK_allowed"]:
#             final_surgery = "PRK"
#             override_reason = "IntraLase predicted but not allowed – switched to PRK."
#         else:
#             final_surgery = "NO_SURGERY"
#             override_reason = "IntraLase predicted but no safe option – NO_SURGERY."

#     # ---- Collect everything in one dictionary ----
#     report = {
#         "patient_code": pid,
#         "eye": eye,
#         "CCT_um": cct,
#         "Kmax_D": kmax,
#         "KC_probability": float(kc_proba),
#         "planned_diopters": float(diopters),
#         "optical_zone_mm": float(oz_mm),
#         "ablation_depth_um": float(ablation),
#         "RSB_um": float(rsb),

#         "safety": safety,                     # full dict with warnings + allowed flags
#         "ml_surgery_prediction": ml_surgery,  # from surgery_model
#         "surgery_probabilities": surgery_probabilities,
#         "final_recommended_surgery": final_surgery,
#         "override_reason": override_reason,
#     }

#     return report

# start_index = 0
# end_index = len(df_clean) - 1

# print(f"df_clean index range = {start_index} → {end_index}")

# idx = 10
# report = decide_surgery_for_case(idx, diopters=3.0, oz_mm=6.0)

# report

"""SHAP"""

# import shap
# import numpy as np

# # --- 1. Convert X to numpy if needed ---
# X_np = np.array(X)

# # --- 2. Initialize SHAP explainer for XGBoost ---
# explainer_surg = shap.TreeExplainer(surgery_model)

# # --- 3. Compute SHAP values for the surgery model ---
# print("Computing SHAP values... this may take ~10–20 seconds")
# surg_shap_values = explainer_surg.shap_values(X_np)

# # --- 4. Map class index → class name ---
# class_names = list(le.classes_)
# num_classes = len(class_names)

# print("Classes:", class_names)

# shap.summary_plot(
#     surg_shap_values,
#     X_np,
#     feature_names=[f"F{j}" for j in range(X_np.shape[1])],
#     plot_type="bar"
# )

# shap.summary_plot(
#     surg_shap_values,
#     X_np,
#     feature_names=[f"F{j}" for j in range(X_np.shape[1])]
# )